### ISSUE TITLE
UnboundLocalError: local variable 'bboxs_pre' referenced before assignment

### ISSUE THREAD

**Issue by anas-zafar** [Vegetebird/MHFormer#16]
Thank you for the amazing work!
```
Traceback (most recent call last):
  File "C:/Users/92336/Desktop/humanposeestimation/MHFormer-main/demo/vis.py", line 278, in <module>
    get_pose2D(video_path, output_dir)
  File "C:/Users/92336/Desktop/humanposeestimation/MHFormer-main/demo/vis.py", line 94, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "C:\Users\92336\Desktop\humanposeestimation\MHFormer-main\demo\lib\hrnet\gen_kpts.py", line 118, in gen_video_kpts
    bboxs = bboxs_pre
UnboundLocalError: local variable 'bboxs_pre' referenced before assignment
```
I am having this issue while trying to run inference. Any fixes for this? @Vegetebird

**Comment by Vegetebird** [comment]
This is a bug when the first frame can not be detected a person, you can clip your video to solve this issue.

**Comment by anas-zafar** [comment]
Thank you @Vegetebird !
