### ISSUE TITLE
inference demo bug

### ISSUE THREAD

**Issue by tiger990111** [Vegetebird/MHFormer#21]
I find a bug when i try to inference a demo.

```
(mhformer) [root@*** ~/MHFormer]# python demo/vis.py --video demo.mp4

Generating 2D pose...
  0%|                                                                                             | 0/791 [00:00<?, ?it/s]No person detected!
  0%|                                                                                             | 0/791 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 276, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 90, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "/root/MHFormer/demo/lib/hrnet/gen_kpts.py", line 113, in gen_video_kpts
    bboxs = bboxs_pre
UnboundLocalError: local variable 'bboxs_pre' referenced before assignmen
```

**Comment by tiger990111** [comment]
It seems that when there's no person in a frame, it will raise error.

**Comment by tiger990111** [comment]
Oh, I find the same issue in #16
