### ISSUE TITLE
demo vis.py a keyError

### ISSUE THREAD

**Issue by Riverzxz** [Vegetebird/MHFormer#32]
Traceback (most recent call last):
  File "demo/vis.py", line 278, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 144, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'trans_auto_1.Temporal_pos_embed'

**Comment by Vegetebird** [comment]
The bug is fixed. You can redownload the repo and pretrained models.

**Comment by Riverzxz** [comment]
thank you!
